### ISSUE TITLE
clicking 

### ISSUE THREAD

**Issue by gitchander** [samirkumardas/pcm-player#15]
I have clicking during playing tone signal.
It fixed if I comment next part:
```
            /* fadein */
            if (i < 50) {
                audioData[i] =  (audioData[i] * i) / 50;
            }
            /* fadeout*/
            if (i >= (length - 51)) {
                audioData[i] =  (audioData[i] * decrement--) / 50;
            }
```
Why did you append this part?

**Comment by samirkumardas** [comment]
To reduce the clicking noise but in your case, it is causing the noise :)
These lines must come with options so that it can be turned off during instanting. Will add when I get some time.

**Comment by gitchander** [comment]
I think growing and fading of signal better to do in first and last packets on side which use feed or sender side.
