### ISSUE TITLE
How can I get the audio gain value?

### ISSUE THREAD

**Issue by ds5qdr** [samirkumardas/pcm-player#17]
I'd like to display VU meter as Audio gain value.

**Comment by elshnkhll** [comment]
This might be helpful https://jsfiddle.net/elshnkhll/p07e5vcq/

**Comment by ds5qdr** [comment]
Thanks, i solved.

**Comment by RSchmitzHH** [comment]
@ds5qdr  Would you share how? Have the same problem. Would be much appreciated, thanks!

**Comment by ds5qdr** [comment]
@RSchmitzHH see below, good luck!
<script>
    var rms_now = rms_avrg = rms_max = rms_gain = 0;

    function calculateRMS(audioBuffer) {
      var sumOfSquares = 0;
      var samples = audioBuffer.getChannelData(0); // Assuming mono audio

      for (var i = 0; i < samples.length; i++) {
        sumOfSquares += samples[i] * samples[i];
      }
      rms_now  = Math.sqrt(sumOfSquares / samples.length);
      rms_gain = 20 * Math.log10(rms_now)

      return rms_gain;
    }
  </script>
