### ISSUE TITLE
Song name

### ISSUE THREAD

**Issue by skyEnrique** [samirkumardas/pcm-player#9]
Our team got an lss with the sample sound. Whats the song title? lol TY

**Comment by samirkumardas** [comment]
lss ?

**Comment by skyEnrique** [comment]
lss. Last song syndrome

**Comment by samirkumardas** [comment]
:) 
https://www.youtube.com/watch?v=7L_n9XgRZ3M
The fact is I never heard this song but my wife used to listen to it while I made this demo.
